name: User Actions
on:
  workflow_dispatch # Change to `push` for automatic runs on code push s

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: dev-fplarache-smartlib-user
  # EKS_CLUSTER: user-eks

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run:  mvn test
        timeout-minutes: 10

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

  #Upload docker image to Amazon Elastic Container Registry (ECR)
  BUILD_AND_PUBLISH:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Build & Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          registry: ${{ secrets.REGISTRY }}
          repo: ${{ env.ECR_REPOSITORY }}
          region: ${{ env.AWS_REGION }}
          tags: latest,${{ github.run_number }}
          daemon_off: false
          dockerfile: ./Dockerfile
          context: ./